import { ArrowRight, BrainCircuit, BriefcaseBusiness, CalendarCheck2, GraduationCap, HeartPulse, Lightbulb, ShieldCheck, Sparkles, Target, Users } from "lucide-react";
import { Link } from "react-router-dom";
import MarketingFooter from "../components/MarketingFooter";
import MarketingHeader from "../components/MarketingHeader";

const principles = [
  { icon: Target, title: "Clarity over complexity", text: "The best productivity system is the one that makes the next right step obvious." },
  { icon: HeartPulse, title: "Ambition without depletion", text: "Student success should include wellbeing, not require sacrificing it." },
  { icon: ShieldCheck, title: "Trust by design", text: "Personal academic and wellness information deserves privacy, transparency, and care." }
];

export default function AboutPage() {
  return (
    <div className="min-h-screen bg-white text-slate-950 dark:bg-[#080a0f] dark:text-white">
      <MarketingHeader />
      <main>
        <section className="relative overflow-hidden px-5 pb-28 pt-40 md:px-8 md:pt-48"><div className="absolute left-1/2 top-20 h-[32rem] w-[48rem] -translate-x-1/2 rounded-full bg-gradient-to-r from-brand-500/15 via-violet-500/15 to-cyan-500/15 blur-[110px]" /><div className="relative mx-auto max-w-5xl text-center"><div className="animate-rise inline-flex items-center gap-2 rounded-full border border-brand-200 bg-brand-50 px-4 py-2 text-[10px] font-bold text-brand-700 dark:border-brand-500/20 dark:bg-brand-500/10 dark:text-brand-300"><Sparkles size={13} /> Our reason for building</div><h1 className="animate-rise delay-100 mt-7 font-display text-5xl font-extrabold leading-[1.04] tracking-[-0.055em] md:text-7xl">College is complex.<br /><span className="bg-gradient-to-r from-brand-600 via-violet-500 to-cyan-500 bg-clip-text text-transparent">Your support system shouldn’t be.</span></h1><p className="animate-rise delay-200 mx-auto mt-7 max-w-2xl text-base leading-8 text-slate-500 dark:text-slate-400">Campus Copilot exists to help every student navigate the demands of school, wellbeing, and career preparation with more clarity—and a little less weight on their shoulders.</p></div></section>

        <section className="border-y border-slate-200/70 bg-slate-50 py-24 dark:border-white/[0.07] dark:bg-white/[0.02]"><div className="mx-auto grid max-w-7xl gap-12 px-5 md:px-8 lg:grid-cols-2 lg:items-center"><div><p className="eyebrow">Our mission</p><h2 className="mt-4 font-display text-4xl font-extrabold tracking-[-0.04em] md:text-5xl">Help students make progress without losing themselves in the process.</h2><p className="mt-6 text-sm leading-7 text-slate-500 dark:text-slate-400">Today’s students manage academics, finances, work, relationships, health, and career pressure across disconnected systems. We bring the signals together so planning becomes more realistic, support becomes more proactive, and success becomes more human.</p></div><div className="relative rounded-[2rem] bg-slate-950 p-7 text-white shadow-2xl dark:bg-[#121620]"><div className="absolute -right-8 -top-8 h-32 w-32 rounded-full bg-brand-500/25 blur-3xl" /><div className="relative grid grid-cols-2 gap-3">{[{ icon: CalendarCheck2, label: "Plan", text: "Turn pressure into clear next steps" }, { icon: BrainCircuit, label: "Predict", text: "Surface risk before it becomes crisis" }, { icon: BriefcaseBusiness, label: "Explore", text: "Connect learning to meaningful work" }, { icon: GraduationCap, label: "Grow", text: "Build confidence across every semester" }].map((item) => <div key={item.label} className="rounded-2xl border border-white/10 bg-white/[0.05] p-5"><item.icon size={20} className="text-brand-300" /><p className="mt-5 font-display text-lg font-bold">{item.label}</p><p className="mt-1 text-[10px] leading-4 text-white/45">{item.text}</p></div>)}</div></div></div></section>

        <section className="mx-auto max-w-7xl px-5 py-28 md:px-8"><div className="text-center"><p className="eyebrow">What guides us</p><h2 className="mx-auto mt-3 max-w-2xl font-display text-4xl font-extrabold tracking-[-0.04em]">Technology should feel like support, not another demand.</h2></div><div className="mt-14 grid gap-5 md:grid-cols-3">{principles.map((item, index) => <article key={item.title} className="group rounded-[1.5rem] border border-slate-200/80 bg-white p-7 transition duration-300 hover:-translate-y-1 hover:shadow-xl dark:border-white/[0.08] dark:bg-[#11141b]"><span className={`grid h-12 w-12 place-items-center rounded-2xl ${index === 0 ? "bg-brand-50 text-brand-600 dark:bg-brand-500/10 dark:text-brand-400" : index === 1 ? "bg-rose-50 text-rose-500 dark:bg-rose-500/10" : "bg-cyan-50 text-cyan-600 dark:bg-cyan-500/10"}`}><item.icon size={21} /></span><h3 className="mt-7 font-display text-xl font-bold">{item.title}</h3><p className="mt-3 text-sm leading-6 text-slate-500 dark:text-slate-400">{item.text}</p></article>)}</div></section>

        <section className="bg-slate-950 px-5 py-28 text-white dark:bg-[#0d1016] md:px-8"><div className="mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-brand-400">Our vision</p><h2 className="mt-4 font-display text-4xl font-extrabold tracking-[-0.04em]">A future where every student has an intelligent advocate.</h2><p className="mt-5 text-sm leading-7 text-white/50">We imagine a platform that notices when a student is falling behind, running on empty, or overlooking a path that fits them—and offers useful support at exactly the right moment.</p></div><div className="space-y-4">{[{ number: "01", title: "Understand the whole student", text: "Academic workload, energy, goals, and career direction belong in one coherent picture." }, { number: "02", title: "Make guidance personal", text: "The right suggestion should reflect the student’s context, not a generic productivity formula." }, { number: "03", title: "Expand access to support", text: "Every student deserves tools that help them plan, recover, and imagine what comes next." }].map((item) => <div key={item.number} className="flex gap-5 rounded-2xl border border-white/10 bg-white/[0.04] p-5"><span className="font-display text-sm font-bold text-brand-400">{item.number}</span><div><h3 className="font-display text-lg font-bold">{item.title}</h3><p className="mt-2 text-xs leading-5 text-white/45">{item.text}</p></div></div>)}</div></div></div></section>

        <section className="px-5 py-28 md:px-8"><div className="mx-auto max-w-5xl rounded-[2rem] bg-gradient-to-br from-brand-600 via-violet-600 to-indigo-700 px-7 py-16 text-center text-white shadow-glow md:px-14"><Users className="mx-auto text-white/70" size={28} /><h2 className="mx-auto mt-5 max-w-2xl font-display text-4xl font-extrabold tracking-[-0.04em]">Build a semester that works for the person you are becoming.</h2><p className="mx-auto mt-4 max-w-lg text-sm leading-6 text-white/60">Explore the workspace and see how Campus Copilot brings academics, wellbeing, and career planning together.</p><Link to="/dashboard" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-white px-6 py-3.5 text-sm font-bold text-slate-950 transition hover:-translate-y-0.5">Explore Campus Copilot <ArrowRight size={16} /></Link></div></section>
      </main>
      <MarketingFooter />
    </div>
  );
}
